### ISSUE TITLE
Numpy Float32 Object not JSON serializable

### ISSUE THREAD

**Issue by petescarth** [RemotePixel/remotepixel-py#1]
In the l8_ndvi_point function, the ratio calculation
`ratio = np.nan_to_num((b5 - b4) / (b5 + b4)) if (b4 * b5) > 0 else 0.`
Returns a float32 that is not JSON serializable and an error in my CloudWatch logs

It seems to work OK with:
`ratio = float(np.nan_to_num((b5 - b4) / (b5 + b4)) if (b4 * b5) > 0 else 0.)`

**Comment by vincentsarago** [comment]
👋 @petescarth thanks for opening this issue 👼 

I fixed this bug with https://github.com/RemotePixel/remotepixel-py/commit/8c7c403a3b236b293f2f83862223850bb674ed03

A new version (0.0.3) of remotepixel-py should be available on pypi.

Vincent
